### ISSUE TITLE
Attiny13

### ISSUE THREAD

**Issue by bamboo-master** [GyverLibs/NecDecoder#1]
Очень хочется подружить attiny13 и пульт, мне нужно всего лишь зажечь светодиод по нажатию кнопки пульта. 
Пока пытаюсь запустить пример (закомментировал все строки с serial для экономии места ), но ничего не компилится, возможно банально не не хватает места.
Вот сами ошибки:
`
C:\Users\9FA5~1\AppData\Local\Temp\ccH161wo.ltrans0.ltrans.o: In function `tick':
C:\Users\����\Documents\Arduino\libraries\NecDecoder\src/NecDecoder.cpp:8: undefined reference to `micros'
collect2.exe: error: ld returned 1 exit status
exit status 1
Ошибка компиляции для платы ATtiny13.

Если закомментировать `attachInterrupt(0, irIsr, FALLING);` то собирается без ошибок и код всего 100 байт, но толку без этой строки нету.

Посоветуйте как можно уместить и чтобы заработало?
`

**Comment by GyverLibs** [comment]
В ядре [MicroCore](https://github.com/MCUdude/MicroCore) есть поддержка micros(). Если не влезет - тут уже писать самому с нуля без использования фреймворка Ардуино, поднимать таймер настраивать его на нужные тайминги

**Comment by bamboo-master** [comment]
Понятно, ожидаемо.

**Comment by GyverLibs** [comment]
А что ожидаемо? С микросом из микрокора всё умещается и отлично работает

**Comment by bamboo-master** [comment]
Ожидаемо что не влезет.
Работает? А что вы в коде написали?
Мне бы посмотреть.
Я то с примером возился 
`#include <NecDecoder.h>
NecDecoder ir;

void setup() {

  attachInterrupt(0, irIsr, FALLING);
}

// в прерывании вызываем tick()
void irIsr() {
  ir.tick();
}

void loop() {
  if (ir.available()) {      

  }
}`

**Comment by bamboo-master** [comment]
Снова, занялся вопросом, все получилось.
